### ISSUE TITLE
Add New Testcases in Problems.csv file

### ISSUE THREAD

**Issue by hirentimbadiya** [hirentimbadiya/Terminal-Quiz#1]
create new mathematics problems in problems.csv file like % , ^ , / , + , -  and also some trigonometry operations like sin / cos = tan

**Comment by VanshSutariya** [comment]
i want this issue

**Comment by brijeshbhikadiya** [comment]
I would like to work on this issue?

**Comment by prince5638** [comment]
I would like to solve this issue, can you please assign to me!

**Comment by bhavymunjani** [comment]
i would like to work on this issue. can you assign

**Comment by meetpaladiya44** [comment]
I would like to work on this issue. can you please assign it to me ?

**Comment by hirentimbadiya** [comment]
Welcome to opensource guys!!
